parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: sk
    database_user: estate
    database_password: real
    
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    
    locale: ru
    secret: e0227b71d7a48fdb77fa32904b7be39c0d3809f1
    database_path: null
